### PR TITLE
Fix/add gallery to events

### LINKED ISSUE #256: seeder: Add real images to the `EventSeeder` gallery

### PR DESCRIPTION
**Pull request by PedroLunet**
Closes #256

### Description of changes

This PR implements the functionality required to persist and display Event Gallery images correctly. Specifically, it includes:

* **DTO & Service Update:** Updated `EventDto` to include the `gallery` field and modified `EventService` to explicitly handle the mapping and persistence of the gallery string list during `create` and `update` operations.
* **Seeder Refactor:** Refactored `EventSeeder` to generate specific, realistic events (e.g., "Workshop de Git", "Jantar de Curso") with matching static filenames instead of purely random Faker data. This ensures the frontend has valid images to display.

# Review checklist
-   [ ] Behavior is as expected
-   [ ] Clean, well structured code
-   [ ] Properly documents API changes in the corresponding controller test
-   [ ] Contains enough appropriate tests
-   [ ] Changes are reflected in the Wiki if necessary

### CODE REVIEW

File: src/main/kotlin/pt/up/fe/ni/website/backend/model/seeders/EventSeeder.kt [hunk 1]
```diff
@@ -41,38 +50,60 @@ class EventSeeder(
...
+                ),
+                SeedEventData(
+                    title = "Sessão de Dúvidas: Kotlin",
+                    description = "Traz as tuas dúvidas sobre desenvolvimento backend.",
+                    image = "workshop_2.png",
+                    gallery = listOf("workshop_1.png"),
+                    category = "Education",
+                    location = "Online (Discord)"
+                )
+            )
```
Comment (peucastro) [inline src/main/kotlin/pt/up/fe/ni/website/backend/model/seeders/EventSeeder.kt]: Thanks for the improvements! The event seeder now uses real images, which is great. However, the image and gallery fields are currently set to just the filename (e.g., "workshop_1.png"). For consistency and to ensure the frontend can find the images, you should use the full static path (e.g., "events/workshop_1.png"), just like it’s done in the `TechnologySeeder`.

**Review by peucastro — CHANGES_REQUESTED** [review]

File: src/main/kotlin/pt/up/fe/ni/website/backend/model/seeders/EventSeeder.kt [hunk 2]
```diff
@@ -13,66 +13,118 @@ import pt.up.fe.ni.website.backend.repository.AccountRepository
...
-@Component @Transactional
+@Component
+@Transactional
 class EventSeeder(
     @Autowired val accountRepository: AccountRepository,
     @Autowired val perActivityRoleRepository: PerActivityRoleRepository,
     @Autowired val entityManager: EntityManager
 ) : AbstractSeeder<EventRepository, Event, Long>(), Logging {
 
+    private val BASE_URL = "http://localhost:8080/static/"
```
Comment (peucastro) [inline src/main/kotlin/pt/up/fe/ni/website/backend/model/seeders/EventSeeder.kt]: To make this more dynamic, it is preferable to use Spring's `ConfigurationPropereties`. It is implemented is this project using the `UploadConfigProperties` class:

```kt
val staticPath = uploadConfigProperties.staticPath?.let {
            ResourceUtils.getFile(it).absolutePath
        } ?: "static"

        val staticFileUploader = StaticFileUploader(
            staticPath,
            uploadConfigProperties.staticServe ?: "localhost:8080"
        )

        val eventsDir = File("$staticPath/events")
        if (!eventsDir.exists()) {
            eventsDir.mkdirs()
            logger.info("Created directory: ${eventsDir.absolutePath}")
        }
```

File: src/main/kotlin/pt/up/fe/ni/website/backend/model/seeders/EventSeeder.kt [hunk 3]
```diff
@@ -13,66 +13,118 @@ import pt.up.fe.ni.website.backend.repository.AccountRepository
...
-            val events = (1..6).map {
-                val title = faker.company().catchPhrase()
-                val description = faker.lorem().sentence(10, 15)
-                val slug = title.lowercase()
+            val customEventsData = listOf(
+                SeedEventData(
+                    title = "Workshop de Git & GitHub",
+                    description = "Aprende as bases de controlo de versões e como colaborar em equipa.",
+                    image = "events/workshop_1.png",
+                    gallery = listOf("events/workshop_2.png", "events/workshop_3.png"),
```
Comment (peucastro) [inline src/main/kotlin/pt/up/fe/ni/website/backend/model/seeders/EventSeeder.kt]: Using the `StaticFileUploader`  we have defined earlier, it is preferable to actually upload the images, similarly  to the `TechnologySeeder`:

```kt
image = staticFileUploader.uploadImage(
                            "events",
                            filename,
                            imageBytes
                        )
```

File: src/main/kotlin/pt/up/fe/ni/website/backend/service/activity/EventService.kt
Comment (peucastro) [inline src/main/kotlin/pt/up/fe/ni/website/backend/service/activity/EventService.kt:1]: The changes in `EventService` that add or update the gallery field directly from the `DTO` should be reverted. Gallery images should only be added through the dedicated upload endpoint (`/events/{idEvent}/gallery`) to ensure proper validation and asset handling.

**Review by peucastro — CHANGES_REQUESTED** [review]

**Review by peucastro — APPROVED** [review]
LGTM ✅ 🚀 💯 🔥 👍 ✈️
