### PR TITLE
Validation and Error Handling

### LINKED ISSUE #7: events: implement middleware for validations
The main job of this issue is to investigate and find the best way to implement middleware in Spring Boot. We need a clean, consistent and scalable way of doing it for all the endpoints.

After that is done, you can simply create an example for the `events/new` endpoint that validates something simple such as a valid date or title with a maximum number of characters

### LINKED ISSUE #15: errors: add global error handling
We should be able to handle general errors globally. For example:
- Invalid endpoints (already implemented)
- Invalid elements accessed by endpoints like `/events/{eventId}`. We should be able to handle this globally with an `@ExceptionHandler` on the `NuSuchElementException`, you have an example in the final minutes of [this video](https://www.youtube.com/watch?v=jiv37i503v4)
- Invalid body when creating resources. For example, when creating an event, if the request is missing one field (e.g. title), you receive an `invalid endpoint` error, which is confusing. We should try to return information about the missing field.
- Any other errors you may see fit

It would also be nice to normalize the errors and have a consistent format, making it easier to handle them in the FE. For example, we could use a JSON format like {"message": "error"} or something similar to this.
You can probably extend the `ErrorController` that already exists

### PR DESCRIPTION
**Pull request by BrunoRosendo**
closes #7 
closes #15 

This PR adds simple validation for the `events` endpoints, serving as example for the other resources. It also introduces error handling with a consistent format of error messages, including validation and other types of errors.

Errors around Jackson and its binding errors are not working as great as I'd want them to. Since I spent way too long hitting my head with this problem, I created #27 and left that problem for later.

# Review checklist
-   [ ] Properly documents API changes in `docs/openapi.yml`
-   [x] Contains enough appropriate tests
-   [x] Behavior is as expected
-   [x] Clean, well structured code

### CODE REVIEW

File: src/main/kotlin/pt/up/fe/ni/website/backend/controller/ErrorController.kt [hunk 1]
```diff
@@ -1,13 +1,89 @@
...
+    @ExceptionHandler(NoSuchElementException::class)
+    @ResponseStatus(HttpStatus.NOT_FOUND)
+    fun elementNotFound(e: NoSuchElementException): CustomError {
+        return wrapSimpleError(e.message ?: "element not found")
+    }
+
+    @ExceptionHandler(Exception::class)
+    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
+    fun unexpectedError(e: Exception): CustomError {
+        System.err.println(e)
```
Comment (limwa) [inline src/main/kotlin/pt/up/fe/ni/website/backend/controller/ErrorController.kt:82]: We should create an issue to use proper logging instead of stdout and stderr

File: src/main/kotlin/pt/up/fe/ni/website/backend/model/Event.kt [hunk 2]
```diff
@@ -1,15 +1,26 @@
 package pt.up.fe.ni.website.backend.model
 
+import com.fasterxml.jackson.annotation.JsonProperty
 import java.util.Date
 import javax.persistence.Entity
 import javax.persistence.GeneratedValue
 import javax.persistence.Id
+import javax.validation.constraints.Size
+import pt.up.fe.ni.website.backend.model.constants.EventConstants as constants
```
Comment (limwa) [inline src/main/kotlin/pt/up/fe/ni/website/backend/model/Event.kt]:
```suggestion
import pt.up.fe.ni.website.backend.model.constants.EventConstants as Constants
```
I would change it to start with a capital letter. This way, it wouldn't be confused with a variable.

File: src/main/kotlin/pt/up/fe/ni/website/backend/model/Event.kt [hunk 3]
```diff
@@ -1,15 +1,26 @@
...
 
 @Entity
 class Event(
+    @JsonProperty(required = true)
```
Comment (limwa) [inline src/main/kotlin/pt/up/fe/ni/website/backend/model/Event.kt:13]: Why are these annotations necessary?

File: src/main/kotlin/pt/up/fe/ni/website/backend/model/Post.kt [hunk 4]
```diff
@@ -8,14 +9,42 @@ import javax.persistence.Entity
 import javax.persistence.EntityListeners
 import javax.persistence.GeneratedValue
 import javax.persistence.Id
+import javax.validation.constraints.NotEmpty
+import javax.validation.constraints.Size
+import pt.up.fe.ni.website.backend.model.constants.PostConstants as constants
```
Comment (limwa) [inline src/main/kotlin/pt/up/fe/ni/website/backend/model/Post.kt]: Same comment as the last one, on the event file

File: src/main/kotlin/pt/up/fe/ni/website/backend/service/PostService.kt [hunk 5]
```diff
@@ -5,23 +5,18 @@ import org.springframework.stereotype.Service
...
     fun getPost(PostId: Long): Post =
-        repository.findByIdOrNull(PostId) ?: throw NoSuchElementException("Post Not Found")
+        repository.findByIdOrNull(PostId) ?: throw NoSuchElementException("post not found with id $PostId")
 
-    fun createPost(post: Post) = repository.save(post)
+    fun createPost(post: Post): Post = repository.save(post)
 
-    fun updatePost(PostId: Long, post: PostDto): Post {
-        val targetPost = repository.findByIdOrNull(PostId) ?: throw NoSuchElementException("Post Not Found")
+    fun updatePost(PostId: Long, post: Post.PatchModel): Post {
```
Comment (limwa) [inline src/main/kotlin/pt/up/fe/ni/website/backend/service/PostService.kt]:
```suggestion
    fun updatePost(postId: Long, post: Post.PatchModel): Post {
```
Since you've changed this line already, can you please fix this?

File: src/main/kotlin/pt/up/fe/ni/website/backend/service/PostService.kt [hunk 6]
```diff
@@ -30,7 +25,7 @@ class PostService(private val repository: PostRepository) {
     }
 
     fun deletePost(PostId: Long): Map<String, String> {
```
Comment (limwa) [inline src/main/kotlin/pt/up/fe/ni/website/backend/service/PostService.kt]:
```suggestion
    fun deletePost(postId: Long): Map<String, String> {
```
Same here

**Review by limwa — CHANGES_REQUESTED** [review]
So far, it's looking good. I'm not particularly fond of having the PatchModel as an inner class, but if the others don't mind, it's fine by me.

**Comment by BrunoRosendo** [comment]
> So far, it's looking good. I'm not particularly fond of having the PatchModel as an inner class, but if the others don't mind, it's fine by me.

I don't think it's perfect either... I wanted to somehow bind it with the model to have validation all in the same place, but I'm definitely taking suggestions regarding this

File: src/main/kotlin/pt/up/fe/ni/website/backend/model/Event.kt (hunk 3 above)
Comment (limwa) [reply src/main/kotlin/pt/up/fe/ni/website/backend/model/Event.kt:13]: To clarify, I'm not saying they aren't needed. I'm just curious about the reason so I can be more careful in my own PRs.

Comment (BrunoRosendo) [reply src/main/kotlin/pt/up/fe/ni/website/backend/model/Event.kt:13]: This annotation makes no difference here. However, I was playing with numerical fields and the annotation is needed in those, otherwise Jackson uses the default value instead of throwing an error. I assume this happens for every class that is mapped to a primitive in Java. I decided to put the annotations everywhere for consistency

Comment (limwa) [reply src/main/kotlin/pt/up/fe/ni/website/backend/model/Event.kt:13]: Thanks!

**Review by limwa — APPROVED** [review]
LGTM! 🚀

Even though the code has vulnerabilities present, as we discovered recently, to fix them falls out of the scope of this PR. We'll have to fix them ASAP though.

Good job! 😁
