### PR TITLE
179 activities change team relationship to manytomany

### LINKED ISSUE #179: activities: change team relationship to ManyToMany
Currently, the teamMembers and hallOfFame fields of the `Activity` entity hold a oneToMany relationship. This is incorrect because an account can be part of multiple teams.

We should change the relationship to ManyToMany

### PR DESCRIPTION
**Pull request by Vidal322**
Closes #179 

# Review checklist
-   [x] Behavior is as expected
-   [ ] Clean, well structured code
-   [ ] Properly documents API changes in the corresponding controller test
-   [ ] Contains enough appropriate tests
-   [ ] Changes are reflected in the Wiki if necessary

### CODE REVIEW

File: src/main/kotlin/pt/up/fe/ni/website/backend/model/Account.kt [hunk 1]
```diff
@@ -40,6 +40,11 @@ class Account(
     @field:Size(min = Constants.Password.minSize, max = Constants.Password.maxSize)
     var password: String,
 
+    @ManyToMany(mappedBy = "teamMembers", fetch = FetchType.EAGER)
+    // @JsonIdentityReference(alwaysAsId = true)
```
Comment (peucastro) [inline src/main/kotlin/pt/up/fe/ni/website/backend/model/Account.kt]:
```suggestion
```

File: src/main/kotlin/pt/up/fe/ni/website/backend/model/Activity.kt [hunk 2]
```diff
@@ -29,8 +32,13 @@ abstract class Activity(
...
 
-    @JoinColumn
-    @OneToMany(fetch = FetchType.EAGER)
+    @ManyToMany(fetch = FetchType.EAGER)
+    @JoinTable(
+        name = "activity_team_members",
+        joinColumns = [JoinColumn(name = "activity_id")],
+        inverseJoinColumns = [JoinColumn(name = "account_id")]
+    )
+    @OrderColumn
```
Comment (peucastro) [inline src/main/kotlin/pt/up/fe/ni/website/backend/model/Activity.kt:41]: Ideally, both `teamMembers` in the `Activiy` model and the `hallOfFame` in the `Project` model should be of type `MutableSet`. This way we won't need the `@OrderColumn` annotation. This can be a little tricky to do, but it will increase the performance, since it will eliminate these unnecessary index management in the database.

**Review by peucastro — CHANGES_REQUESTED** [review]

**Review by peucastro — APPROVED** [review]
Thank you for this! 🫡 ✅ ✈️
