### PR TITLE
Fix/delete unused files

### LINKED ISSUE #177: files: delete files when not being used
Currently, accounts, projects and events are storing their images even if the entities are deleted or their images are changed. We should delete them in these cases in order to save space.

### PR DESCRIPTION
**Pull request by PedroOliveira42**
Closes #177 

Added and tested code to delete unused files in the backend
# Review checklist
-   [X] Behavior is as expected
-   [X] Clean, well structured code
-   [X] Properly documents API changes in the corresponding controller test
-   [X] Contains enough appropriate tests (due to fileuploader nature only tested manually)
-   [X] Changes are reflected in the Wiki if necessary (No change was assumed necessary)

### CODE REVIEW

File: src/main/kotlin/pt/up/fe/ni/website/backend/service/AccountService.kt [hunk 1]
```diff
@@ -71,8 +74,10 @@ class AccountService(
     }
 
     fun deleteAccountById(id: Long) {
-        if (!repository.existsById(id)) {
-            throw NoSuchElementException(ErrorMessages.accountNotFound(id))
+        val account = getAccountById(id)
+
+        account.photo?.takeIf { it.isNotBlank() }?.let { photo ->
+            fileUploader.deleteImage(photo)
```
Comment (MRita443) [inline src/main/kotlin/pt/up/fe/ni/website/backend/service/AccountService.kt]: So this looks good right, it first checks if the account photo is not null, and then if it's not an empty string. Only then it deletes the photo. But I don't think it's needed because we have the `    @field:NullOrNotBlank` annotation on the `photo` field, so it will never be blank, only null

File: src/main/kotlin/pt/up/fe/ni/website/backend/service/activity/AbstractActivityService.kt [hunk 2]
```diff
@@ -106,4 +109,13 @@ abstract class AbstractActivityService<T : Activity>(
...
     }
+
+    protected fun removeAllActivityImages(activityImage: String, activityGallery: MutableList<String>) {
+        fileUploader.deleteImage(activityImage)
+        activityGallery.forEach { imageName ->
+            if (imageName.isNotBlank()) {
+                fileUploader.deleteImage(imageName)
+            }
+        }
+    }
```
Comment (MRita443) [inline src/main/kotlin/pt/up/fe/ni/website/backend/service/activity/AbstractActivityService.kt]:
```suggestion
    protected fun removeAllActivityImages(activityImage: String, activityGallery: MutableList<String>) {
        fileUploader.deleteImage(activityImage)
        activityGallery.forEach { imagePath ->
            if (imagePath.isNotBlank()) {
                fileUploader.deleteImage(imagePath)
            }
        }
    }
```

File: src/main/kotlin/pt/up/fe/ni/website/backend/service/activity/EventService.kt [hunk 3]
```diff
@@ -38,10 +38,11 @@ class EventService(
     }
 
     fun deleteEventById(eventId: Long) {
-        if (!repository.existsById(eventId)) {
-            throw NoSuchElementException(ErrorMessages.eventNotFound(eventId))
-        }
-
+        val event = getEventById(eventId)
+            ?: throw NoSuchElementException(ErrorMessages.eventNotFound(eventId))
```
Comment (MRita443) [inline src/main/kotlin/pt/up/fe/ni/website/backend/service/activity/EventService.kt]:
```suggestion
```

The Elvis operator is not needed because `getEventById` does that already :)

File: src/main/kotlin/pt/up/fe/ni/website/backend/service/activity/ProjectService.kt [hunk 4]
```diff
@@ -51,11 +51,12 @@ class ProjectService(
     }
 
     fun deleteProjectById(id: Long) {
-        if (!repository.existsById(id)) {
-            throw NoSuchElementException(ErrorMessages.projectNotFound(id))
-        }
-
+        val project = getProjectById(id)
+            ?: throw NoSuchElementException(ErrorMessages.projectNotFound(id))
```
Comment (MRita443) [inline src/main/kotlin/pt/up/fe/ni/website/backend/service/activity/ProjectService.kt]:
```suggestion
```
Same here

File: src/main/kotlin/pt/up/fe/ni/website/backend/service/AccountService.kt [hunk 5]
```diff
@@ -49,8 +49,11 @@ class AccountService(
         }
 
         dto.photoFile?.let {
+            val previousPhoto = account.photo
             val fileName = fileUploader.buildFileName(it, dto.email)
             account.photo = fileUploader.uploadImage("profile", fileName, it.bytes)
+            previousPhoto?.let { fileUploader.deleteImage(it) }
+            // This seems like it should be inside a try catch, but no db changes are, ask in next meet
```
Comment (MRita443) [inline src/main/kotlin/pt/up/fe/ni/website/backend/service/AccountService.kt]: I don't think this is needed because that kind of treatment is already done either in the `deleteImage` function or in the functions it calls

**Review by MRita443 — CHANGES_REQUESTED** [review]
Great job! Really minor things

**Review by rubuy-74 — APPROVED** [review]
Just tested it and it works perfectly. Nice work :rocket:

**Review by MRita443 — APPROVED** [review]
